import type { KospiTicker } from "./tickers";

// US 대형주 (S&P 500 / 나스닥 메가캡 위주, 거래대금 상위 종목)
export const US_TICKERS: KospiTicker[] = [
  { ticker: "AAPL", name: "Apple", sector: "Technology" },
  { ticker: "MSFT", name: "Microsoft", sector: "Technology" },
  { ticker: "NVDA", name: "NVIDIA", sector: "Technology" },
  { ticker: "AMZN", name: "Amazon", sector: "Consumer Discretionary" },
  { ticker: "GOOGL", name: "Alphabet (A)", sector: "Communication Services" },
  { ticker: "GOOG", name: "Alphabet (C)", sector: "Communication Services" },
  { ticker: "META", name: "Meta Platforms", sector: "Communication Services" },
  { ticker: "TSLA", name: "Tesla", sector: "Consumer Discretionary" },
  { ticker: "BRK-B", name: "Berkshire Hathaway", sector: "Financials" },
  { ticker: "AVGO", name: "Broadcom", sector: "Technology" },
  { ticker: "JPM", name: "JPMorgan Chase", sector: "Financials" },
  { ticker: "LLY", name: "Eli Lilly", sector: "Healthcare" },
  { ticker: "V", name: "Visa", sector: "Financials" },
  { ticker: "UNH", name: "UnitedHealth", sector: "Healthcare" },
  { ticker: "XOM", name: "ExxonMobil", sector: "Energy" },
  { ticker: "MA", name: "Mastercard", sector: "Financials" },
  { ticker: "PG", name: "Procter & Gamble", sector: "Consumer Staples" },
  { ticker: "JNJ", name: "Johnson & Johnson", sector: "Healthcare" },
  { ticker: "HD", name: "Home Depot", sector: "Consumer Discretionary" },
  { ticker: "COST", name: "Costco", sector: "Consumer Staples" },
  { ticker: "ORCL", name: "Oracle", sector: "Technology" },
  { ticker: "ABBV", name: "AbbVie", sector: "Healthcare" },
  { ticker: "BAC", name: "Bank of America", sector: "Financials" },
  { ticker: "NFLX", name: "Netflix", sector: "Communication Services" },
  { ticker: "KO", name: "Coca-Cola", sector: "Consumer Staples" },
  { ticker: "CVX", name: "Chevron", sector: "Energy" },
  { ticker: "MRK", name: "Merck", sector: "Healthcare" },
  { ticker: "WMT", name: "Walmart", sector: "Consumer Staples" },
  { ticker: "AMD", name: "AMD", sector: "Technology" },
  { ticker: "PEP", name: "PepsiCo", sector: "Consumer Staples" },
  { ticker: "ADBE", name: "Adobe", sector: "Technology" },
  { ticker: "CRM", name: "Salesforce", sector: "Technology" },
  { ticker: "TMO", name: "Thermo Fisher", sector: "Healthcare" },
  { ticker: "MCD", name: "McDonald's", sector: "Consumer Discretionary" },
  { ticker: "CSCO", name: "Cisco", sector: "Technology" },
  { ticker: "ACN", name: "Accenture", sector: "Technology" },
  { ticker: "ABT", name: "Abbott Labs", sector: "Healthcare" },
  { ticker: "LIN", name: "Linde", sector: "Materials" },
  { ticker: "WFC", name: "Wells Fargo", sector: "Financials" },
  { ticker: "DIS", name: "Walt Disney", sector: "Communication Services" },
  { ticker: "INTC", name: "Intel", sector: "Technology" },
  { ticker: "DHR", name: "Danaher", sector: "Healthcare" },
  { ticker: "VZ", name: "Verizon", sector: "Communication Services" },
  { ticker: "TXN", name: "Texas Instruments", sector: "Technology" },
  { ticker: "IBM", name: "IBM", sector: "Technology" },
  { ticker: "PM", name: "Philip Morris", sector: "Consumer Staples" },
  { ticker: "GE", name: "GE Aerospace", sector: "Industrials" },
  { ticker: "AMGN", name: "Amgen", sector: "Healthcare" },
  { ticker: "CAT", name: "Caterpillar", sector: "Industrials" },
  { ticker: "QCOM", name: "Qualcomm", sector: "Technology" },
  { ticker: "NOW", name: "ServiceNow", sector: "Technology" },
  { ticker: "GS", name: "Goldman Sachs", sector: "Financials" },
  { ticker: "ISRG", name: "Intuitive Surgical", sector: "Healthcare" },
  { ticker: "BKNG", name: "Booking Holdings", sector: "Consumer Discretionary" },
  { ticker: "RTX", name: "RTX", sector: "Industrials" },
  { ticker: "AXP", name: "American Express", sector: "Financials" },
  { ticker: "T", name: "AT&T", sector: "Communication Services" },
  { ticker: "SPGI", name: "S&P Global", sector: "Financials" },
  { ticker: "MS", name: "Morgan Stanley", sector: "Financials" },
  { ticker: "PFE", name: "Pfizer", sector: "Healthcare" },
  { ticker: "BLK", name: "BlackRock", sector: "Financials" },
  { ticker: "PLTR", name: "Palantir", sector: "Technology" },
  { ticker: "UBER", name: "Uber", sector: "Industrials" },
  { ticker: "INTU", name: "Intuit", sector: "Technology" },
  { ticker: "BX", name: "Blackstone", sector: "Financials" },
  { ticker: "AMAT", name: "Applied Materials", sector: "Technology" },
  { ticker: "NEE", name: "NextEra Energy", sector: "Utilities" },
  { ticker: "HON", name: "Honeywell", sector: "Industrials" },
  { ticker: "BA", name: "Boeing", sector: "Industrials" },
  { ticker: "C", name: "Citigroup", sector: "Financials" },
  { ticker: "SCHW", name: "Charles Schwab", sector: "Financials" },
  { ticker: "TJX", name: "TJX Companies", sector: "Consumer Discretionary" },
  { ticker: "BSX", name: "Boston Scientific", sector: "Healthcare" },
  { ticker: "MU", name: "Micron Technology", sector: "Technology" },
  { ticker: "PGR", name: "Progressive", sector: "Financials" },
  { ticker: "LMT", name: "Lockheed Martin", sector: "Industrials" },
  { ticker: "SYK", name: "Stryker", sector: "Healthcare" },
  { ticker: "VRTX", name: "Vertex Pharma", sector: "Healthcare" },
  { ticker: "CB", name: "Chubb", sector: "Financials" },
  { ticker: "ETN", name: "Eaton", sector: "Industrials" },
  { ticker: "GILD", name: "Gilead Sciences", sector: "Healthcare" },
  { ticker: "MDT", name: "Medtronic", sector: "Healthcare" },
  { ticker: "DE", name: "Deere", sector: "Industrials" },
  { ticker: "ADP", name: "ADP", sector: "Industrials" },
  { ticker: "ANET", name: "Arista Networks", sector: "Technology" },
  { ticker: "MMC", name: "Marsh & McLennan", sector: "Financials" },
  { ticker: "PANW", name: "Palo Alto Networks", sector: "Technology" },
  { ticker: "LRCX", name: "Lam Research", sector: "Technology" },
  { ticker: "REGN", name: "Regeneron", sector: "Healthcare" },
  { ticker: "TMUS", name: "T-Mobile US", sector: "Communication Services" },
  { ticker: "ELV", name: "Elevance Health", sector: "Healthcare" },
  { ticker: "ZTS", name: "Zoetis", sector: "Healthcare" },
  { ticker: "KLAC", name: "KLA", sector: "Technology" },
  { ticker: "MO", name: "Altria", sector: "Consumer Staples" },
  { ticker: "SHW", name: "Sherwin-Williams", sector: "Materials" },
  { ticker: "CMCSA", name: "Comcast", sector: "Communication Services" },
  { ticker: "NKE", name: "Nike", sector: "Consumer Discretionary" },
  { ticker: "SO", name: "Southern Company", sector: "Utilities" },
  { ticker: "DUK", name: "Duke Energy", sector: "Utilities" },
  { ticker: "ICE", name: "Intercontinental Exchange", sector: "Financials" },
  { ticker: "ADI", name: "Analog Devices", sector: "Technology" },
  { ticker: "USB", name: "U.S. Bancorp", sector: "Financials" },
  { ticker: "EQIX", name: "Equinix", sector: "Real Estate" },
  { ticker: "CME", name: "CME Group", sector: "Financials" },
  { ticker: "SBUX", name: "Starbucks", sector: "Consumer Discretionary" },
  { ticker: "AMT", name: "American Tower", sector: "Real Estate" },
  { ticker: "PYPL", name: "PayPal", sector: "Financials" },
  { ticker: "MDLZ", name: "Mondelez", sector: "Consumer Staples" },
  { ticker: "FI", name: "Fiserv", sector: "Financials" },
  { ticker: "CI", name: "Cigna", sector: "Healthcare" },
  { ticker: "CDNS", name: "Cadence Design", sector: "Technology" },
  { ticker: "SNPS", name: "Synopsys", sector: "Technology" },
  { ticker: "MCO", name: "Moody's", sector: "Financials" },
  { ticker: "CVS", name: "CVS Health", sector: "Healthcare" },
  { ticker: "FDX", name: "FedEx", sector: "Industrials" },
  { ticker: "TGT", name: "Target", sector: "Consumer Staples" },
  { ticker: "COIN", name: "Coinbase", sector: "Financials" },
  { ticker: "MSTR", name: "MicroStrategy", sector: "Technology" },
  { ticker: "ABNB", name: "Airbnb", sector: "Consumer Discretionary" },
  { ticker: "SHOP", name: "Shopify", sector: "Technology" },
  { ticker: "MRVL", name: "Marvell Technology", sector: "Technology" },
  { ticker: "ORLY", name: "O'Reilly Auto", sector: "Consumer Discretionary" },
  { ticker: "PLD", name: "Prologis", sector: "Real Estate" },
  { ticker: "CRWD", name: "CrowdStrike", sector: "Technology" },
  { ticker: "WELL", name: "Welltower", sector: "Real Estate" },
  { ticker: "TFC", name: "Truist Financial", sector: "Financials" },
  { ticker: "PNC", name: "PNC Financial", sector: "Financials" },
  { ticker: "F", name: "Ford Motor", sector: "Consumer Discretionary" },
  { ticker: "GM", name: "General Motors", sector: "Consumer Discretionary" },
  { ticker: "RIVN", name: "Rivian", sector: "Consumer Discretionary" },
  { ticker: "LCID", name: "Lucid Group", sector: "Consumer Discretionary" },
  { ticker: "SOFI", name: "SoFi Technologies", sector: "Financials" },
  { ticker: "HOOD", name: "Robinhood Markets", sector: "Financials" },
  { ticker: "SNOW", name: "Snowflake", sector: "Technology" },
  { ticker: "DDOG", name: "Datadog", sector: "Technology" },
  { ticker: "NET", name: "Cloudflare", sector: "Technology" },
  { ticker: "SQ", name: "Block", sector: "Financials" },
  { ticker: "ROKU", name: "Roku", sector: "Communication Services" },
  { ticker: "RBLX", name: "Roblox", sector: "Communication Services" },
  { ticker: "PINS", name: "Pinterest", sector: "Communication Services" },
  { ticker: "SNAP", name: "Snap", sector: "Communication Services" },
  { ticker: "SPOT", name: "Spotify", sector: "Communication Services" },
  { ticker: "CHWY", name: "Chewy", sector: "Consumer Discretionary" },
  { ticker: "DKNG", name: "DraftKings", sector: "Consumer Discretionary" },
  { ticker: "TSM", name: "TSMC ADR", sector: "Technology" },
  { ticker: "ASML", name: "ASML ADR", sector: "Technology" },
  { ticker: "BABA", name: "Alibaba ADR", sector: "Consumer Discretionary" },
  { ticker: "PDD", name: "PDD Holdings", sector: "Consumer Discretionary" },
  { ticker: "JD", name: "JD.com ADR", sector: "Consumer Discretionary" },
  { ticker: "NIO", name: "NIO ADR", sector: "Consumer Discretionary" },
  { ticker: "BIDU", name: "Baidu ADR", sector: "Communication Services" },
  { ticker: "SE", name: "Sea Limited", sector: "Communication Services" },
  { ticker: "MELI", name: "MercadoLibre", sector: "Consumer Discretionary" },
];

const seen = new Set<string>();
export const US_TICKERS_UNIQUE = US_TICKERS.filter((t) => {
  if (seen.has(t.ticker)) return false;
  seen.add(t.ticker);
  return true;
});
